title: Create a travel chess set
hero_image: images/banner.png
description: "Design and 3D print or laser cut a travel chess set"
version: 4
listed: false
copyedit: false
last_tested: "2019-05-10"
steps:
  - title: Introduction
  - title: Make pawns and rooks
  - title: Make the king
  - title: Make the queen
  - title: Make the knights
  - title: Make the bishops
  - title: Make the board
  - title: Manufacture the board
  - title: "What next?"

