title: freecad-chess-set
hero_image: images/banner.png
description: freecad-chess-set description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-10"
steps:
  - title: Introduction
  - title: Pawns and Rooks
  - title: The King
  - title: The Queen
  - title: Knights
  - title: Bishops
  - title: The board
  - title: Producing the board
  - title: Printing the pieces.

